data:
  dataset: file_path
  file_path: './data/fandisk/input/fandisk.ply'
  gt_path: './data/fandisk/gt/fandisk.obj'
  non_manifold_sampling: gaussian
  sample_type: grid
  n_points: 20000
  n_samples: 10000
  eval_res: 256
  sapmling_std: 0.005
  grid_range: 1.1
  shuffle: true

model:
  init_type: siren
  nl: sine
  decoder_hidden_dim: 256
  decoder_n_hidden_layers: 4
  latent_size: 0
  sphere_init_params: [1.6, 0.1]

loss:
  name: neur_cad_recon_fd
  type: odw_default
  div_type: l1
  div_decay: linear
  eikonal_type: abs
  decay_params: [10, 0.2, 10, 0.5, 0.001, 0]
  weights: [7000, 600, 0, 50, 0, 1, 0]
  offset_h: 0.1
  offset_d: 0.1
  d_offset_start: 0.1
  d_offset_end: 0.05
  bidirectional_morse: false
  morse_near: true
  finite_difference: true
  use_near_points: true
  use_denominator: false
  use_iters: true
  udf: false

exp:
  log_dir: logs/neur_cad_recon_fd/default
  seed: 42
  num_epochs: 1
  batch_size: 1
  lr: 5.0e-5
  grad_clip_norm: 10.0
  weight_decay: 0.0
  improvement_patience: 3
  eval_frequency: 500
  chunk_size: 5000
  early_stop: false
  output_any: false
